gobin:
    build: docker/
    links:
        - redis
        - rabbit
    ports:
        - "9901:9001"
    volumes:
        - .:/code

redis:
    image: redis:2.8.19

rabbitdata:
    image: busybox
    volumes:
        - /data/mnesia

rabbit:
    image: rabbitmq:3-management
    volumes_from:
        - rabbitdata
    ports:
        - "15672:15672"
